// Build-time only: generate public/frontend/bible-data.gen.js from the
// TypeScript sources of truth (src/books.ts, src/translations.ts) so the
// frontend can parse references and resolve translations without a build step.
//
// Run: npm run gen:frontend  (commit the generated file)

import { writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { BOOKS } from "../src/books.ts";
import { TRANSLATIONS } from "../src/translations.ts";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT_FILE = join(__dirname, "..", "public", "frontend", "bible-data.gen.js");

async function main() {
  const books = BOOKS.map((b) => ({ name: b.name, file: b.file, aliases: b.aliases ?? [] }));
  const code = [
    "// GENERATED by scripts/gen-frontend-data.ts — do not edit by hand.",
    "// Source of truth: src/books.ts and src/translations.ts.",
    `export const BOOKS = ${JSON.stringify(books)};`,
    `export const TRANSLATIONS = ${JSON.stringify(TRANSLATIONS)};`,
    "",
  ].join("\n");
  await writeFile(OUT_FILE, code, "utf8");
  console.log(`Wrote ${books.length} books, ${TRANSLATIONS.length} translations -> ${OUT_FILE}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
